### PR TITLE
🎨 Store `collectExpiryAt` in Firebase DateTime format

### PR DESCRIPTION
**Pull request by WeiJun0827**

### CODE REVIEW

**Comment by WeiJun0827** [comment]
@williamchong do you know why the first commit code doesn't work?

**Comment by williamchong** [comment]
> @williamchong do you know why the first commit code doesn't work?

How does it "not work"?

**Comment by WeiJun0827** [comment]
> How does it "not work"?

It runs OK at my local, but it can't pass the `npm run test`.

**Comment by williamchong** [comment]
> > How does it "not work"?
> 
> It runs OK at my local, but it can't pass the `npm run test`.

Our firestore stub used for test doesn't have Timestamp stub and exported i guess

**Comment by WeiJun0827** [comment]
> Our firestore stub used for test doesn't have Timestamp stub and exported i guess

Oh, it makes sense, thanks!

**Review by williamchong — APPROVED** [review]

**Pull request merged**
