### PR TITLE
✨ Add update ts to invalidate avatar cache

### PR DESCRIPTION
**Pull request by williamchong**

### CODE REVIEW

**Review by WeiJun0827 — COMMENTED** [review]
How will `/users/id/:id/avatar` handle the `ts`?

**Comment by williamchong** [comment]
> How will `/users/id/:id/avatar` handle the `ts`?

it won't be handled, it is just for bypassing the existing cache for each ts/canonical

**Comment by WeiJun0827** [comment]
> > How will `/users/id/:id/avatar` handle the `ts`?
> 
> it won't be handled, it is just for bypassing the existing cache for each ts/canonical

Curious about why could we bypass the cache by just adding `tx`?

**Comment by williamchong** [comment]
> > > How will `/users/id/:id/avatar` handle the `ts`?
> > 
> > 
> > it won't be handled, it is just for bypassing the existing cache for each ts/canonical
> 
> Curious about why could we bypass the cache by just adding `tx`?

You can often add random querystring behind any url to bypass cache
Most of the time the cache key is the whole url, so it does not use the same cache when qs is different

**Comment by WeiJun0827** [comment]
I see, thanks!! 🙏🏻

**Review by WeiJun0827 — APPROVED** [review]

**Pull request merged**
